import { describe, it, expect } from 'vitest';
import { cssGenerator, formatCssValue, expandCompositeToken } from './css.js';
import { resolveDocument } from '../core/resolver.js';
import { parseTokenDocument } from '../core/parser.js';
import type { ResolvedToken } from '../core/types.js';

const generate = (raw: unknown): string => {
  const tokens = resolveDocument(parseTokenDocument(raw));
  const [artifact] = cssGenerator.generate(tokens, { version: '0.1.0' });
  if (artifact === undefined) throw new Error('css generator produced no artifact');
  return artifact.content;
};

const token = (path: readonly string[], type: ResolvedToken['type'], value: ResolvedToken['value']): ResolvedToken => ({
  path,
  id: path.join('.'),
  name: path[path.length - 1]!,
  type,
  value,
});

describe('css generator', () => {
  it('emits a :root block with kebab-case custom properties', () => {
    const css = generate({
      color: { $type: 'color', primary: { $value: '#1a73e8' } },
      spacing: { $type: 'dimension', small: { $value: '8px' } },
    });
    expect(css).toContain(':root {');
    expect(css).toContain('--color-primary: #1a73e8;');
    expect(css).toContain('--spacing-small: 8px;');
    expect(css.trim().endsWith('}')).toBe(true);
  });

  it('includes the generated-by header comment', () => {
    const css = generate({ color: { $type: 'color', primary: { $value: '#1a73e8' } } });
    expect(css.startsWith('/* Generated by toki v0.1.0 — do not edit */')).toBe(true);
  });

  it('is deterministic — identical input produces byte-identical output', () => {
    const raw = {
      color: {
        $type: 'color',
        primary: { $value: '#1a73e8' },
        secondary: { $value: '{color.primary}' },
      },
      spacing: { $type: 'dimension', small: { $value: '8px' }, medium: { $value: '16px' } },
    };
    expect(generate(raw)).toBe(generate(raw));
  });

  it('emits resolved reference values (not the raw {…} syntax)', () => {
    const css = generate({
      color: {
        $type: 'color',
        primary: { $value: '#1a73e8' },
        secondary: { $value: '{color.primary}' },
      },
    });
    expect(css).toContain('--color-secondary: #1a73e8;');
    expect(css).not.toContain('{color.primary}');
  });

  it('formats cubicBezier tokens as a CSS cubic-bezier() function', () => {
    const css = generate({
      motion: { $type: 'cubicBezier', ease: { $value: [0.4, 0, 0.2, 1] } },
    });
    expect(css).toContain('--motion-ease: cubic-bezier(0.4, 0, 0.2, 1);');
  });

  it('formats single shadow objects and multi-shadow arrays', () => {
    const css = generate({
      shadow: {
        $type: 'shadow',
        sm: { $value: { x: 0, y: 4, blur: 8, color: 'rgba(0,0,0,0.25)' } },
        lg: {
          $value: [
            { x: 0, y: 4, blur: 8, color: 'rgba(0,0,0,0.25)' },
            { x: 0, y: 12, blur: 24, spread: 0, color: 'rgba(0,0,0,0.15)' },
          ],
        },
      },
    });
    expect(css).toContain('--shadow-sm: 0 4 8 rgba(0,0,0,0.25);');
    expect(css).toContain('--shadow-lg: 0 4 8 rgba(0,0,0,0.25), 0 12 24 0 rgba(0,0,0,0.15);');
  });

  it('expands typography tokens into longhand CSS custom properties', () => {
    const css = generate({
      type: {
        $type: 'typography',
        body: { $value: { fontSize: '16px', lineHeight: '1.5', fontFamily: 'Inter', fontWeight: '400' } },
      },
      color: { $type: 'color', primary: { $value: '#fff' } },
    });
    expect(css).toContain('--type-body-font-family: Inter;');
    expect(css).toContain('--type-body-font-size: 16px;');
    expect(css).toContain('--type-body-font-weight: 400;');
    expect(css).toContain('--type-body-line-height: 1.5;');
    expect(css).toContain('--color-primary: #fff;');
  });

  it('expands partial typography tokens (only defined fields)', () => {
    const css = generate({
      type: {
        $type: 'typography',
        body: { $value: { fontSize: '16px', fontWeight: '400' } },
      },
    });
    expect(css).toContain('--type-body-font-size: 16px;');
    expect(css).toContain('--type-body-font-weight: 400;');
    expect(css).not.toContain('--type-body-font-family');
    expect(css).not.toContain('--type-body-line-height');
  });

  it('expands border tokens into longhand CSS custom properties', () => {
    const css = generate({
      border: {
        $type: 'border',
        default: { $value: { width: '1px', style: 'solid', color: '#e0e0e0' } },
      },
    });
    expect(css).toContain('--border-default-color: #e0e0e0;');
    expect(css).toContain('--border-default-style: solid;');
    expect(css).toContain('--border-default-width: 1px;');
  });

  it('expands transition tokens into longhand CSS custom properties', () => {
    const css = generate({
      transition: {
        $type: 'transition',
        fast: { $value: { duration: '200ms', timingFunction: 'ease-in-out', delay: '0ms' } },
      },
    });
    expect(css).toContain('--transition-fast-delay: 0ms;');
    expect(css).toContain('--transition-fast-duration: 200ms;');
    expect(css).toContain('--transition-fast-timing-function: ease-in-out;');
  });

  it('skips composite tokens with non-object values gracefully', () => {
    const t = token(['type', 'body'], 'typography', 'not-an-object' as unknown as ResolvedToken['value']);
    const expanded = expandCompositeToken(t);
    expect(expanded).toEqual([]);
  });

  it('formatCssValue returns undefined for unsupported composite types', () => {
    expect(formatCssValue(token(['type', 'body'], 'typography', { fontSize: '16px' }))).toBeUndefined();
  });

  it('writes to the css/ subdirectory', () => {
    const [artifact] = cssGenerator.generate(
      resolveDocument(parseTokenDocument({ color: { $type: 'color', a: { $value: '#fff' } } })),
      { version: '0.1.0' },
    );
    expect(artifact?.relativePath).toBe('css/tokens.css');
    expect(artifact?.format).toBe('css');
  });

  it('emits a README.md artifact for the output subdirectory', () => {
    const artifacts = cssGenerator.generate(
      resolveDocument(parseTokenDocument({ color: { $type: 'color', a: { $value: '#fff' } } })),
      { version: '0.1.0' },
    );
    const readme = artifacts.find((a) => a.relativePath === 'css/README.md');
    expect(readme).toBeDefined();
    expect(readme?.content).toContain('<!-- Generated by toki v0.1.0 — do not edit -->');
  });

  it('matches the tokens.css snapshot', () => {
    const css = generate({
      color: {
        $type: 'color',
        primary: { $value: '#1a73e8' },
        secondary: { $value: '{color.primary}' },
      },
      spacing: { $type: 'dimension', small: { $value: '8px' }, medium: { $value: '16px' } },
      motion: { $type: 'cubicBezier', ease: { $value: [0.4, 0, 0.2, 1] } },
    });
    expect(css).toMatchSnapshot();
  });
});
