import { describe, it, expect } from "vitest";
import { cssGenerator, formatCssValue } from "./css.js";
import { resolveDocument } from "../core/resolver.js";
import { parseTokenDocument } from "../core/parser.js";
import type { ResolvedToken } from "../core/types.js";

const generate = (raw: unknown): string => {
  const tokens = resolveDocument(parseTokenDocument(raw));
  const [artifact] = cssGenerator.generate(tokens, { version: "0.1.0" });
  if (artifact === undefined) throw new Error("css generator produced no artifact");
  return artifact.content;
};

const token = (
  path: readonly string[],
  type: ResolvedToken["type"],
  value: ResolvedToken["value"],
): ResolvedToken => ({
  path,
  id: path.join("."),
  name: path[path.length - 1]!,
  type,
  value,
});

describe("css generator", () => {
  it("emits a :root block with kebab-case custom properties", () => {
    const css = generate({
      color: { $type: "color", primary: { $value: "#1a73e8" } },
      spacing: { $type: "dimension", small: { $value: "8px" } },
    });
    expect(css).toContain(":root {");
    expect(css).toContain("--color-primary: #1a73e8;");
    expect(css).toContain("--spacing-small: 8px;");
    expect(css.trim().endsWith("}")).toBe(true);
  });

  it("includes the generated-by header comment", () => {
    const css = generate({ color: { $type: "color", primary: { $value: "#1a73e8" } } });
    expect(css.startsWith("/* Generated by toki v0.1.0 — do not edit */")).toBe(true);
  });

  it("is deterministic — identical input produces byte-identical output", () => {
    const raw = {
      color: {
        $type: "color",
        primary: { $value: "#1a73e8" },
        secondary: { $value: "{color.primary}" },
      },
      spacing: { $type: "dimension", small: { $value: "8px" }, medium: { $value: "16px" } },
    };
    expect(generate(raw)).toBe(generate(raw));
  });

  it("emits resolved reference values (not the raw {…} syntax)", () => {
    const css = generate({
      color: {
        $type: "color",
        primary: { $value: "#1a73e8" },
        secondary: { $value: "{color.primary}" },
      },
    });
    expect(css).toContain("--color-secondary: #1a73e8;");
    expect(css).not.toContain("{color.primary}");
  });

  it("formats cubicBezier tokens as a CSS cubic-bezier() function", () => {
    const css = generate({
      motion: { $type: "cubicBezier", ease: { $value: [0.4, 0, 0.2, 1] } },
    });
    expect(css).toContain("--motion-ease: cubic-bezier(0.4, 0, 0.2, 1);");
  });

  it("formats single shadow objects and multi-shadow arrays", () => {
    const css = generate({
      shadow: {
        $type: "shadow",
        sm: { $value: { x: 0, y: 4, blur: 8, color: "rgba(0,0,0,0.25)" } },
        lg: {
          $value: [
            { x: 0, y: 4, blur: 8, color: "rgba(0,0,0,0.25)" },
            { x: 0, y: 12, blur: 24, spread: 0, color: "rgba(0,0,0,0.15)" },
          ],
        },
      },
    });
    expect(css).toContain("--shadow-sm: 0 4 8 rgba(0,0,0,0.25);");
    expect(css).toContain(
      "--shadow-lg: 0 4 8 rgba(0,0,0,0.25), 0 12 24 0 rgba(0,0,0,0.15);",
    );
  });

  it("skips multi-property composite types (typography/border/transition)", () => {
    const css = generate({
      type: {
        $type: "typography",
        body: { $value: { fontSize: "16px", lineHeight: "1.5" } },
      },
      color: { $type: "color", primary: { $value: "#fff" } },
    });
    expect(css).not.toContain("--type-body");
    expect(css).toContain("--color-primary: #fff;");
  });

  it("emits an empty (but valid) :root block when nothing is CSS-eligible", () => {
    const css = generate({
      type: { $type: "typography", body: { $value: { fontSize: "16px" } } },
    });
    expect(css).toContain(":root {");
    expect(css).toContain("}");
  });

  it("formatCssValue returns undefined for unsupported composite types", () => {
    expect(
      formatCssValue(token(["type", "body"], "typography", { fontSize: "16px" })),
    ).toBeUndefined();
  });

  it("writes to the css/ subdirectory", () => {
    const [artifact] = cssGenerator.generate(
      resolveDocument(parseTokenDocument({ color: { $type: "color", a: { $value: "#fff" } } })),
      { version: "0.1.0" },
    );
    expect(artifact?.relativePath).toBe("css/tokens.css");
    expect(artifact?.format).toBe("css");
  });
});