import { describe, it, expect } from 'vitest';
import { reactNativeGenerator } from './react-native.js';
import { resolveDocument } from '../core/resolver.js';
import { parseTokenDocument } from '../core/parser.js';
import { generateFromDocument } from '../core/pipeline.js';
import { transformTokens } from '../core/transformer.js';
import type { ResolvedToken } from '../core/types.js';
import { GeneratorError } from '../utils/errors.js';

/** Full fixture exercising every category, pre-transformed for RN. */
const FIXTURE = {
  color: {
    $type: 'color',
    primary: { $value: '#1A73E8' },
    secondary: { $value: '{color.primary}' },
    brand: { accent: { $value: '#f80' } },
  },
  spacing: { $type: 'dimension', small: { $value: '8px' }, page: { $value: '1.5rem' } },
  font: { $type: 'fontFamily', sans: { $value: 'Inter, sans-serif' } },
  weight: { $type: 'fontWeight', strong: { $value: 'bold' } },
  type: {
    $type: 'typography',
    body: { $value: { fontFamily: 'Inter, sans-serif', fontSize: '16px', fontWeight: 'bold' } },
  },
  shadow: {
    $type: 'shadow',
    sm: { $value: { x: 0, y: 4, blur: 8, color: 'rgba(0,0,0,0.25)' } },
  },
};

/** Resolve + run the RN transform stage (mirrors the pipeline). */
const rnTokens = (raw: unknown): readonly ResolvedToken[] =>
  transformTokens(resolveDocument(parseTokenDocument(raw)), 'react-native');

const generate = (raw: unknown) => {
  const artifacts = reactNativeGenerator.generate(rnTokens(raw), { version: '0.1.0' });
  const byPath = (suffix: string): string => {
    const artifact = artifacts.find((a) => a.relativePath === `react-native/${suffix}`);
    if (artifact === undefined) throw new Error(`missing artifact react-native/${suffix}`);
    return artifact.content;
  };
  return { artifacts, tokensJs: byPath('tokens.js'), stylesJs: byPath('styles.js') };
};

describe('react-native generator — tokens.js', () => {
  it('groups tokens by pluralized category with nested paths preserved', () => {
    const { tokensJs } = generate(FIXTURE);
    expect(tokensJs).toContain('export const colors = {');
    expect(tokensJs).toContain('export const spacing = {');
    expect(tokensJs).toContain('brand: {');
    expect(tokensJs).toContain('accent: "#ff8800"');
  });

  it('emits dimensions as raw numbers (dp), including rem conversion', () => {
    const { tokensJs } = generate(FIXTURE);
    expect(tokensJs).toContain('small: 8,');
    expect(tokensJs).toContain('page: 24,');
    expect(tokensJs).not.toContain('"8px"');
  });

  it('normalizes fontWeight, fontFamily, typography and shadow values for RN', () => {
    const { tokensJs } = generate(FIXTURE);
    expect(tokensJs).toContain('strong: "700"');
    expect(tokensJs).toContain('sans: "Inter"');
    expect(tokensJs).toContain('body: { fontFamily: "Inter", fontSize: 16, fontWeight: "700" }');
    expect(tokensJs).toContain('shadowRadius: 4');
  });

  it('normalizes hex colors via the transform stage', () => {
    const { tokensJs } = generate(FIXTURE);
    expect(tokensJs).toContain('primary: "#1a73e8"');
    expect(tokensJs).toContain('secondary: "#1a73e8"');
  });

  it('exports single-segment tokens as flat scalars', () => {
    const { tokensJs } = generate({ brand: { $type: 'color', $value: '#fff' } });
    // `#fff` is normalized to `#ffffff` by the transform stage.
    expect(tokensJs).toContain('export const brand = "#ffffff";');
  });

  it('throws GeneratorError when two tokens collapse to the same camelCase key', () => {
    // `brand-primary` and `brandPrimary` both become `brandPrimary`.
    expect(() =>
      generate({
        color: {
          $type: 'color',
          'brand-primary': { $value: '#fff' },
          brandPrimary: { $value: '#000' },
        },
      }),
    ).toThrow(GeneratorError);
  });

  it('throws GeneratorError when a group would nest under a leaf token', () => {
    // `color.brand` is a leaf; `color.Brand.primary` camelCases to the same key.
    expect(() =>
      generate({
        color: {
          $type: 'color',
          brand: { $value: '#fff' },
          Brand: { primary: { $value: '#000' } },
        },
      }),
    ).toThrow(GeneratorError);
  });

  it('includes the header comment and is deterministic', () => {
    const a = generate(FIXTURE).tokensJs;
    expect(a.startsWith('/* Generated by toki v0.1.0 — do not edit */')).toBe(true);
    expect(a).toBe(generate(FIXTURE).tokensJs);
  });

  it('matches the tokens.js snapshot', () => {
    expect(generate(FIXTURE).tokensJs).toMatchSnapshot();
  });
});

describe('react-native generator — styles.js', () => {
  it('derives backgrounds, textColors and textStyles with StyleSheet.create()', () => {
    const { stylesJs } = generate(FIXTURE);
    expect(stylesJs).toContain('import { StyleSheet } from "react-native";');
    expect(stylesJs).toContain('import { colors, types } from "./tokens.js";');
    expect(stylesJs).toContain('export const backgrounds = StyleSheet.create({');
    expect(stylesJs).toContain('primary: { backgroundColor: colors.primary },');
    expect(stylesJs).toContain('brandAccent: { backgroundColor: colors.brand.accent },');
    expect(stylesJs).toContain('export const textColors = StyleSheet.create({');
    expect(stylesJs).toContain('primary: { color: colors.primary },');
    expect(stylesJs).toContain('export const textStyles = StyleSheet.create({');
    expect(stylesJs).toContain('body: types.body,');
  });

  it('omits groups with no source tokens and their imports', () => {
    const { stylesJs } = generate({
      spacing: { $type: 'dimension', small: { $value: '8px' } },
    });
    expect(stylesJs).not.toContain('backgrounds');
    expect(stylesJs).not.toContain('from "./tokens.js"');
    expect(stylesJs).toContain('export const styles = StyleSheet.create({});');
  });

  it('uses bracket references for digit-leading keys', () => {
    const { stylesJs } = generate({
      color: { $type: 'color', '500': { $value: '#fff' } },
    });
    expect(stylesJs).toContain('_500: { backgroundColor: colors["500"] },');
  });

  it('matches the styles.js snapshot', () => {
    expect(generate(FIXTURE).stylesJs).toMatchSnapshot();
  });
});

describe('react-native generator — artifacts + pipeline integration', () => {
  it('writes tokens.js, styles.js and README.md under react-native/', () => {
    const { artifacts } = generate(FIXTURE);
    expect(artifacts.map((a) => a.relativePath).sort()).toEqual([
      'react-native/README.md',
      'react-native/styles.js',
      'react-native/tokens.js',
    ]);
    expect(artifacts.every((a) => a.format === 'react-native')).toBe(true);
  });

  it('pipeline applies the RN transform stage (dimensions → numbers)', () => {
    const result = generateFromDocument(parseTokenDocument(FIXTURE), ['react-native']);
    const tokensJs = result.artifacts.find((a) => a.relativePath === 'react-native/tokens.js');
    expect(tokensJs?.content).toContain('small: 8,');
  });
});
