import { describe, it, expect } from "vitest";
import { platformReadme } from "./readme.js";
import { ALL_FORMATS } from "../core/types.js";

describe("platform READMEs", () => {
  it("renders a README for every output format", () => {
    for (const format of ALL_FORMATS) {
      const readme = platformReadme(format, "0.1.0");
      expect(readme.startsWith("<!-- Generated by toki v0.1.0 — do not edit -->")).toBe(true);
      expect(readme).toContain("## Quick start");
      expect(readme).toContain("## Naming convention");
      expect(readme).toContain("## Known limitations");
      expect(readme.toLowerCase()).toContain("multi-theme");
    }
  });

  it("documents the RN unit conventions", () => {
    const readme = platformReadme("react-native", "0.1.0");
    expect(readme).toContain("dp");
    expect(readme).toContain("sp");
    expect(readme).toContain("StyleSheet");
  });

  it("documents @use for angular latest and @import-only for angular-11", () => {
    expect(platformReadme("angular", "0.1.0")).toContain("@use");
    const legacy = platformReadme("angular-11", "0.1.0");
    expect(legacy).toContain("@import");
    expect(legacy).toContain("no `@use`/`@forward`");
  });

  it("documents the React nested theme shape", () => {
    const readme = platformReadme("react", "0.1.0");
    expect(readme).toContain("theme.colors");
    expect(readme).toContain("next-themes");
  });
});
