import { describe, it, expect } from 'vitest';
import { svelteGenerator } from './svelte.js';
import { resolveDocument } from '../core/resolver.js';
import { parseTokenDocument } from '../core/parser.js';
import { GeneratorError } from '../utils/errors.js';

const FIXTURE = {
  color: {
    $type: 'color',
    primary: { $value: '#1a73e8' },
    secondary: { $value: '{color.primary}' },
  },
  spacing: { $type: 'dimension', small: { $value: '8px' } },
  type: {
    $type: 'typography',
    body: { $value: { fontSize: '16px', lineHeight: '1.5' } },
  },
};

const generate = (raw: unknown) => {
  const tokens = resolveDocument(parseTokenDocument(raw));
  const artifacts = svelteGenerator.generate(tokens, { version: '0.1.0' });
  const byPath = (suffix: string): string => {
    const artifact = artifacts.find((a) => a.relativePath === `svelte/${suffix}`);
    if (artifact === undefined) throw new Error(`missing artifact svelte/${suffix}`);
    return artifact.content;
  };
  return { artifacts, css: byPath('tokens.css'), ts: byPath('tokens.ts') };
};

describe('svelte generator', () => {
  it('emits :root CSS custom properties consumable from scoped <style> blocks', () => {
    const { css } = generate(FIXTURE);
    expect(css).toContain(':root {');
    expect(css).toContain('--color-primary: #1a73e8;');
    expect(css).toContain('--color-secondary: #1a73e8;');
    expect(css).toContain('--spacing-small: 8px;');
    expect(css).toContain('--type-body-font-size: 16px;');
    expect(css).toContain('--type-body-line-height: 1.5;');
  });

  it('emits a camelCase ES module with every token', () => {
    const { ts } = generate(FIXTURE);
    expect(ts).toContain('export const colorPrimary = "#1a73e8";');
    expect(ts).toContain('export const colorSecondary = "#1a73e8";');
    expect(ts).toContain('export const spacingSmall = "8px";');
    expect(ts).toContain('export const typeBody = {"fontSize":"16px","lineHeight":"1.5"};');
  });

  it('throws GeneratorError on identifier collisions', () => {
    expect(() =>
      generate({
        color: {
          $type: 'color',
          'brand-primary': { $value: '#fff' },
          brandPrimary: { $value: '#000' },
        },
      }),
    ).toThrow(GeneratorError);
  });

  it('writes tokens.css, tokens.ts and README.md under svelte/', () => {
    const { artifacts } = generate(FIXTURE);
    expect(artifacts.map((a) => a.relativePath).sort()).toEqual([
      'svelte/README.md',
      'svelte/tokens.css',
      'svelte/tokens.ts',
    ]);
    expect(artifacts.every((a) => a.format === 'svelte')).toBe(true);
  });

  it('includes the header comment and is deterministic', () => {
    const { css, ts } = generate(FIXTURE);
    expect(css.startsWith('/* Generated by toki v0.1.0 — do not edit */')).toBe(true);
    expect(ts.startsWith('/* Generated by toki v0.1.0 — do not edit */')).toBe(true);
    expect(ts).toBe(generate(FIXTURE).ts);
  });

  it('matches the artifact snapshots', () => {
    const { css, ts } = generate(FIXTURE);
    expect(css).toMatchSnapshot();
    expect(ts).toMatchSnapshot();
  });
});
