/**
 * Output schema publication (P9): per-platform JSON Schema documents.
 *
 * For every output format, `toki schema` publishes a draft-07 JSON Schema that
 * describes the *JSON view* of that platform's generated artifacts for the
 * given token set:
 *
 * - **css / tailwind** — the custom-property map: `{ "--color-primary": ... }`
 * - **js / angular / angular-11 / svelte / vue** — the named-export object:
 *   `{ "colorPrimary": ... }` (CONSTANT_CASE for Angular)
 * - **react-native / react** — the grouped category object:
 *   `{ "colors": { "primary": ... } }`
 * - **stencil** — camelCase exports plus the grouped `tokens` object
 *
 * Schemas are generated from the *resolved* tokens (platform transforms
 * applied, mirroring what each generator sees), list every emitted key in
 * `properties` with `additionalProperties: false`, and can be associated with
 * JSON documents in editors (e.g. VS Code `json.schemas`) for autocomplete
 * and validation.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { NamingConvention, OutputFormat, ResolvedToken } from '../core/types.js';
import { ALL_FORMATS } from '../core/types.js';
import { parseTokenDocument, parseTokenJson, readTokenFileRaw } from '../core/parser.js';
import { resolveDocument } from '../core/resolver.js';
import { transformTokens } from '../core/transformer.js';
import { GeneratorError } from '../utils/errors.js';
import { themePath } from '../utils/format.js';
import { toCamelCase, toKebabCase, getNamingFunction } from '../utils/naming.js';
import { expandCompositeToken, formatCssValue, isCompositeType } from '../generators/css.js';
import { makeIdentifier } from '../generators/js.js';
import { buildVarName, resolveNamespace, tailwindCompositeDeclarations } from '../generators/tailwind.js';
import { categoryName } from '../utils/grouping.js';

/** A JSON Schema (draft-07) document describing one platform's output view. */
export type OutputSchema = Readonly<Record<string, unknown>>;

/** Options for building a per-format output schema. */
export interface OutputSchemaOptions {
  /** Naming convention override. Defaults to the format's artifact naming. */
  readonly naming?: NamingConvention;
}

const SCHEMA_DRAFT = 'http://json-schema.org/draft-07/schema#';

/** Default naming convention per format, mirroring each generator's artifact. */
const SCHEMA_DEFAULT_NAMING: Readonly<Record<OutputFormat, NamingConvention>> = {
  css: 'kebab-case',
  js: 'camelCase',
  'react-native': 'camelCase',
  angular: 'CONSTANT_CASE',
  'angular-11': 'CONSTANT_CASE',
  svelte: 'camelCase',
  react: 'camelCase',
  stencil: 'camelCase',
  vue: 'camelCase',
  tailwind: 'kebab-case',
};

const TITLES: Readonly<Record<OutputFormat, string>> = {
  css: 'Toki CSS output schema',
  js: 'Toki JavaScript output schema',
  'react-native': 'Toki React Native output schema',
  angular: 'Toki Angular output schema',
  'angular-11': 'Toki Angular 11 output schema',
  svelte: 'Toki Svelte output schema',
  react: 'Toki React / Next.js output schema',
  stencil: 'Toki StencilJS output schema',
  vue: 'Toki Vue output schema',
  tailwind: 'Toki Tailwind CSS v4 output schema',
};

const DESCRIPTIONS: Readonly<Record<OutputFormat, string>> = {
  css: 'JSON view of the artifacts generated by toki for the "css" format: the :root custom-property map.',
  js: 'JSON view of the artifacts generated by toki for the "js" format: the named-export object (tokens.js).',
  'react-native':
    'JSON view of the artifacts generated by toki for the "react-native" format: the grouped category object (tokens.js).',
  angular:
    'JSON view of the artifacts generated by toki for the "angular" format: the CONSTANT_CASE export object (tokens.ts).',
  'angular-11':
    'JSON view of the artifacts generated by toki for the "angular-11" format: the CONSTANT_CASE export object (tokens.ts).',
  svelte:
    'JSON view of the artifacts generated by toki for the "svelte" format: the ES-module export object (tokens.ts).',
  react: 'JSON view of the artifacts generated by toki for the "react" format: the nested theme object (theme.ts).',
  stencil:
    'JSON view of the artifacts generated by toki for the "stencil" format: the camelCase exports plus the grouped tokens object (tokens.ts).',
  vue: 'JSON view of the artifacts generated by toki for the "vue" format: the ES-module export object (tokens.ts).',
  tailwind:
    'JSON view of the artifacts generated by toki for the "tailwind" format: the @theme custom-property map (tokens.css).',
};

/** Attach the token description to a schema fragment when present. */
const describe = (schema: Record<string, unknown>, token: ResolvedToken): Record<string, unknown> => {
  if (token.description !== undefined && token.description.length > 0) {
    return { ...schema, description: token.description };
  }
  return schema;
};

/** Map a resolved token value to its JSON Schema fragment. */
const valueSchema = (value: unknown): Record<string, unknown> => {
  if (typeof value === 'string') return { type: 'string' };
  if (typeof value === 'number') return { type: 'number' };
  if (typeof value === 'boolean') return { type: 'boolean' };
  if (Array.isArray(value)) {
    if (value.length === 0) return { type: 'array' };
    const first = value[0];
    if (first === undefined) return { type: 'array' };
    return { type: 'array', items: valueSchema(first) };
  }
  if (value !== null && typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const properties: Record<string, unknown> = {};
    for (const key of Object.keys(obj).toSorted()) {
      const entry = obj[key];
      if (entry === undefined) continue;
      properties[key] = valueSchema(entry);
    }
    return { type: 'object', properties, additionalProperties: false };
  }
  return {};
};

/** Wrap a property map in the standard schema envelope. */
const envelope = (format: OutputFormat, properties: Record<string, unknown>): OutputSchema => ({
  $schema: SCHEMA_DRAFT,
  $id: `https://toki.design/schema/output/${format}.json`,
  title: TITLES[format],
  description: DESCRIPTIONS[format],
  type: 'object',
  additionalProperties: false,
  properties,
  required: Object.keys(properties).toSorted(),
});

/** CSS-style custom-property properties (`--kebab-case`), composites expanded. */
const cssProperties = (tokens: readonly ResolvedToken[], naming: NamingConvention): Record<string, unknown> => {
  const namingFn = getNamingFunction(naming);
  const properties: Record<string, unknown> = {};
  for (const token of tokens) {
    if (isCompositeType(token.type)) {
      for (const decl of expandCompositeToken(token, namingFn)) {
        properties[`--${decl.property}`] = describe({ type: 'string' }, token);
      }
      continue;
    }
    if (formatCssValue(token) === undefined) continue;
    properties[`--${namingFn(token.path)}`] = describe({ type: 'string' }, token);
  }
  return properties;
};

/**
 * Named-export properties (`camelCase` / `CONSTANT_CASE`), mirroring the JS
 * family generators. Identifier collisions throw like the generators do.
 */
const identifierProperties = (tokens: readonly ResolvedToken[], naming: NamingConvention): Record<string, unknown> => {
  const properties: Record<string, unknown> = {};
  const seen = new Map<string, string>();
  for (const token of tokens) {
    const identifier = makeIdentifier(token.path, naming);
    const collision = seen.get(identifier);
    if (collision !== undefined) {
      throw new GeneratorError(
        `Identifier collision: tokens "${collision}" and "${token.id}" both map to ` +
          `export name "${identifier}". Rename one of the tokens.`,
      );
    }
    seen.set(identifier, token.id);
    properties[identifier] = describe(valueSchema(token.value), token);
  }
  return properties;
};

/** camelCase leaf key for a path segment (mirrors the grouped generators). */
const leafKey = (segment: string): string => {
  const key = toCamelCase([segment]);
  return key.length > 0 ? key : segment;
};

/**
 * Category subtrees (`colors`, `spacing`, …). `pluralize` mirrors
 * `categoryName` (react-native / react); `false` keeps the raw first path
 * segment (stencil's grouped `tokens` object).
 */
const categoryTree = (
  tokens: readonly ResolvedToken[],
  naming: NamingConvention,
  pluralize: boolean,
): Record<string, unknown> => {
  const categories: Record<string, unknown> = {};
  const claimed = new Map<string, string>();
  for (const token of tokens) {
    const [first, ...rest] = token.path;
    if (first === undefined || rest.length === 0) continue;
    const category = pluralize ? categoryName(first) : first;
    if (!claimed.has(category)) {
      claimed.set(category, token.id);
      categories[category] = { type: 'object', properties: {}, additionalProperties: false };
    }
    const rootProps = (categories[category] as Record<string, unknown>)['properties'] as Record<string, unknown>;
    let current = rootProps;
    for (let i = 0; i < rest.length; i++) {
      const key = leafKey(rest[i] as string);
      const isLast = i === rest.length - 1;
      if (isLast) {
        if (current[key] !== undefined) {
          throw new GeneratorError(
            `Key collision in category "${category}": token "${token.id}" maps to the same ` +
              `key "${key}" as an existing entry. Rename one of the tokens.`,
          );
        }
        current[key] = describe(valueSchema(token.value), token);
      } else {
        let child = current[key];
        if (child === undefined) {
          child = { type: 'object', properties: {}, additionalProperties: false };
          current[key] = child;
        } else if (typeof child !== 'object' || Array.isArray(child)) {
          throw new GeneratorError(
            `Token "${token.id}" cannot be nested under the existing leaf key "${key}" ` +
              `in category "${category}". Rename one of the tokens.`,
          );
        }
        current = (child as Record<string, unknown>)['properties'] as Record<string, unknown>;
      }
    }
  }
  return categories;
};

/** Grouped-category properties (react-native / react): categories + scalars. */
const groupProperties = (tokens: readonly ResolvedToken[], naming: NamingConvention): Record<string, unknown> => {
  const properties = categoryTree(tokens, naming, true);
  const claimed = new Set(Object.keys(properties));
  for (const token of tokens) {
    const [first, ...rest] = token.path;
    if (first !== undefined && rest.length > 0) continue;
    const key = makeIdentifier(token.path, naming);
    if (claimed.has(key)) {
      throw new GeneratorError(
        `Key collision: token "${token.id}" maps to property "${key}" which is already ` +
          `used by a token category. Rename one of the tokens.`,
      );
    }
    claimed.add(key);
    properties[key] = describe(valueSchema(token.value), token);
  }
  return properties;
};

/** Stencil properties: camelCase exports plus the grouped `tokens` object. */
const stencilProperties = (tokens: readonly ResolvedToken[], naming: NamingConvention): Record<string, unknown> => {
  const properties = identifierProperties(tokens, naming);
  properties['tokens'] = {
    type: 'object',
    description: 'Grouped token object keyed by raw first path segment.',
    properties: categoryTree(tokens, naming, false),
    additionalProperties: false,
  };
  return properties;
};

/** Tailwind `@theme` custom-property properties (namespace-mapped). */
const tailwindProperties = (tokens: readonly ResolvedToken[], naming: NamingConvention): Record<string, unknown> => {
  const namingFn = getNamingFunction(naming);
  const properties: Record<string, unknown> = {};
  for (const token of tokens) {
    if (isCompositeType(token.type)) {
      for (const decl of tailwindCompositeDeclarations(token, namingFn)) {
        properties[decl.varName] = describe({ type: 'string' }, token);
      }
      continue;
    }
    const namespace = resolveNamespace(token);
    if (namespace === undefined) continue;
    if (formatCssValue(token) === undefined) continue;
    const varName = buildVarName(token, namespace, namingFn);
    properties[varName] = describe({ type: 'string' }, token);
  }
  return properties;
};

/**
 * Build the output JSON Schema for a single format from resolved tokens.
 * The value side mirrors what the platform's generator emits (platform
 * transforms already applied by the caller).
 */
export const buildOutputSchema = (
  format: OutputFormat,
  tokens: readonly ResolvedToken[],
  options: OutputSchemaOptions = {},
): OutputSchema => {
  const naming = options.naming ?? SCHEMA_DEFAULT_NAMING[format];
  let properties: Record<string, unknown>;
  switch (format) {
    case 'css':
      properties = cssProperties(tokens, naming);
      break;
    case 'js':
    case 'svelte':
    case 'vue':
    case 'angular':
    case 'angular-11':
      properties = identifierProperties(tokens, naming);
      break;
    case 'react-native':
    case 'react':
      properties = groupProperties(tokens, naming);
      break;
    case 'stencil':
      properties = stencilProperties(tokens, naming);
      break;
    case 'tailwind':
      properties = tailwindProperties(tokens, naming);
      break;
  }
  return envelope(format, properties);
};

/** Build output schemas for several formats. */
export const buildOutputSchemas = (
  tokens: readonly ResolvedToken[],
  formats: readonly OutputFormat[],
  options: OutputSchemaOptions = {},
): ReadonlyMap<OutputFormat, OutputSchema> => {
  const schemas = new Map<OutputFormat, OutputSchema>();
  for (const format of formats) {
    schemas.set(format, buildOutputSchema(format, tokens, options));
  }
  return schemas;
};

/** Options for the `toki schema` command handler. */
export interface GenerateOutputSchemasOptions {
  readonly input: string;
  readonly output: string;
  readonly formats?: readonly OutputFormat[];
  readonly naming?: Partial<Record<OutputFormat, NamingConvention>>;
  readonly theme?: string;
}

/**
 * Read, parse, resolve, and transform a token file, then publish one JSON
 * Schema per requested format under `output`. Returns the written relative
 * paths.
 */
export const generateOutputSchemas = async (options: GenerateOutputSchemasOptions): Promise<readonly string[]> => {
  const formats = options.formats ?? ALL_FORMATS;
  const raw = await readTokenFileRaw(options.input);
  const doc = parseTokenDocument(parseTokenJson(raw, options.input), options.input);
  const tokens = resolveDocument(doc);

  await mkdir(options.output, { recursive: true });
  const written: string[] = [];
  for (const format of formats) {
    const naming = options.naming?.[format];
    const transformed = transformTokens(tokens, format);
    const schema = buildOutputSchema(format, transformed, naming !== undefined ? { naming } : {});
    const relativePath = options.theme !== undefined ? themePath(`${format}.json`, options.theme) : `${format}.json`;
    await writeFile(join(options.output, relativePath), `${JSON.stringify(schema, null, 2)}\n`, 'utf8');
    written.push(relativePath);
  }
  return written;
};

/** Convert a token path to its CSS custom property name (`--kebab-case`). */
export const toCssVariable = (path: readonly string[]): string => `--${toKebabCase(path)}`;
