/**
 * Output formatting helpers shared across generators.
 *
 * Generators are responsible for converting resolved `TokenValue`s to
 * platform-idiomatic string representations. These helpers centralize the
 * common bits: the file header comment, JSON-value stringification, and
 * value formatting primitives.
 */

/** Generate the standard `Generated by toki` header comment. */
export const headerComment = (version: string): string =>
  `/* Generated by toki v${version} — do not edit */`;

/** HTML-comment variant of the header, for Markdown artifacts. */
export const headerCommentHtml = (version: string): string =>
  `<!-- Generated by toki v${version} — do not edit -->`;

/**
 * Format a resolved token value as a string for inclusion in output.
 *
 * - Strings are returned as-is (the caller decides whether to quote them).
 * - Numbers are converted via `String()`.
 * - Booleans → `"true"`/`"false"`.
 * - Composite values are serialized as JSON (deterministic, sorted keys).
 * - Arrays are serialized as JSON.
 */
export const formatValue = (value: unknown): string => {
  if (typeof value === "string") return value;
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (value === null || value === undefined) return "null";
  return JSON.stringify(sortKeys(value));
};

/** Format a value as a JS literal (strings double-quoted, others as-is). */
export const formatJsValue = (value: unknown): string => {
  if (typeof value === "string") return JSON.stringify(value);
  return formatValue(value);
};

/** Deterministic key sort for JSON serialization. */
const sortKeys = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(obj).toSorted()) {
      out[key] = sortKeys(obj[key]);
    }
    return out;
  }
  return value;
};

/** Join a path array into a dotted identifier. */
export const joinPath = (path: readonly string[]): string => path.join(".");
