import { describe, it, expect } from 'vitest';
import { headerComment, headerCommentHtml, formatValue, formatJsValue, joinPath, themePath } from './format.js';

describe('headerComment', () => {
  it('renders the standard header with version', () => {
    expect(headerComment('1.0.0')).toBe('/* Generated by toki v1.0.0 — do not edit */');
  });
});

describe('headerCommentHtml', () => {
  it('renders the HTML-comment header with version', () => {
    expect(headerCommentHtml('2.0.0')).toBe('<!-- Generated by toki v2.0.0 — do not edit -->');
  });
});

describe('formatValue', () => {
  it('returns strings as-is', () => {
    expect(formatValue('#1a73e8')).toBe('#1a73e8');
    expect(formatValue('')).toBe('');
  });

  it('converts finite numbers via String()', () => {
    expect(formatValue(42)).toBe('42');
    expect(formatValue(1.5)).toBe('1.5');
    expect(formatValue(0)).toBe('0');
    expect(formatValue(-10)).toBe('-10');
  });

  it('returns null for non-finite numbers', () => {
    expect(formatValue(NaN)).toBe('null');
    expect(formatValue(Infinity)).toBe('null');
    expect(formatValue(-Infinity)).toBe('null');
  });

  it('converts booleans to "true" or "false"', () => {
    expect(formatValue(true)).toBe('true');
    expect(formatValue(false)).toBe('false');
  });

  it('returns "null" for null and undefined', () => {
    expect(formatValue(null)).toBe('null');
    expect(formatValue(undefined)).toBe('null');
  });

  it('serializes objects as JSON with sorted keys', () => {
    expect(formatValue({ b: 2, a: 1 })).toBe('{"a":1,"b":2}');
  });

  it('serializes arrays as JSON', () => {
    expect(formatValue([1, 2, 3])).toBe('[1,2,3]');
  });

  it('sorts nested object keys deterministically', () => {
    expect(formatValue({ z: { b: 2, a: 1 }, a: [3, 2, 1] })).toBe('{"a":[3,2,1],"z":{"a":1,"b":2}}');
  });
});

describe('formatJsValue', () => {
  it('wraps strings in double quotes', () => {
    expect(formatJsValue('#1a73e8')).toBe('"#1a73e8"');
    expect(formatJsValue('hello')).toBe('"hello"');
  });

  it('passes non-strings through formatValue', () => {
    expect(formatJsValue(42)).toBe('42');
    expect(formatJsValue(true)).toBe('true');
    expect(formatJsValue({ a: 1 })).toBe('{"a":1}');
  });
});

describe('joinPath', () => {
  it('joins path segments with dots', () => {
    expect(joinPath(['color', 'brand', 'primary'])).toBe('color.brand.primary');
  });

  it('handles a single segment', () => {
    expect(joinPath(['color'])).toBe('color');
  });

  it('returns empty string for empty path', () => {
    expect(joinPath([])).toBe('');
  });
});

describe('themePath', () => {
  it('inserts theme suffix before the extension', () => {
    expect(themePath('css/tokens.css', 'light')).toBe('css/tokens.light.css');
  });

  it('handles double extensions like .d.ts', () => {
    expect(themePath('js/tokens.d.ts', 'dark')).toBe('js/tokens.dark.d.ts');
  });

  it('does not theme README files', () => {
    expect(themePath('css/README.md', 'light')).toBe('css/README.md');
  });

  it('handles files without extensions', () => {
    expect(themePath('angular/tokens', 'light')).toBe('angular/tokens.light');
  });

  it('handles top-level files (no directory)', () => {
    expect(themePath('tokens.css', 'dark')).toBe('tokens.dark.css');
  });
});
