import { describe, it, expect } from "vitest";
import { runPipeline, generateFromDocument } from "./pipeline.js";
import { parseTokenDocument } from "./parser.js";
import { writeArtifacts } from "../utils/writer.js";
import { resolveFormats } from "../generators/index.js";
import { rm, mkdir, readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";

const sampleDoc = {
  color: {
    $type: "color",
    primary: { $value: "#1a73e8" },
    secondary: { $value: "{color.primary}" },
  },
  spacing: { $type: "dimension", small: { $value: "8px" } },
};

const uniqueDir = async (): Promise<string> => {
  const dir = join(tmpdir(), `toki-test-${randomUUID()}`);
  await mkdir(dir, { recursive: true });
  return dir;
};

describe("pipeline", () => {
  it("runs parse → resolve → generate in memory and returns artifacts", async () => {
    // Write the sample token file to disk so runPipeline can read it.
    const inputDir = await uniqueDir();
    const inputPath = join(inputDir, "tokens.json");
    await writeFile(inputPath, JSON.stringify(sampleDoc), "utf8");

    const result = await runPipeline({
      input: inputPath,
      formats: ["css", "js"],
    });
    expect(result.tokenCount).toBe(3);
    expect(result.formats).toEqual(["css", "js"]);
    const paths = result.artifacts.map((a) => a.relativePath);
    expect(paths).toContain("css/tokens.css");
    expect(paths).toContain("js/tokens.js");
    expect(paths).toContain("js/tokens.d.ts");
    // CSS artifact carries the resolved reference (no raw {…} left).
    const css = result.artifacts.find((a) => a.relativePath === "css/tokens.css");
    expect(css?.content).toContain("--color-secondary: #1a73e8;");
  });

  it("generateFromDocument resolves and generates without disk I/O", () => {
    const result = generateFromDocument(parseTokenDocument(sampleDoc), ["css"]);
    expect(result.artifacts).toHaveLength(1);
    expect(result.artifacts[0]?.relativePath).toBe("css/tokens.css");
  });

  it("walks the full end-to-end flow via the writer (clean default)", async () => {
    const inputDir = await uniqueDir();
    const inputPath = join(inputDir, "tokens.json");
    await writeFile(inputPath, JSON.stringify(sampleDoc), "utf8");
    const outputDir = await uniqueDir();

    const result = await runPipeline({ input: inputPath, formats: ["css", "js"] });
    const writeResult = await writeArtifacts(outputDir, result.artifacts, { clean: true });

    expect(writeResult.written.length).toBeGreaterThan(0);
    const cssPath = writeResult.written.find((p) => p.endsWith("css/tokens.css"));
    expect(cssPath).toBeDefined();
    const written = await readFile(cssPath!, "utf8");
    expect(written.startsWith("/* Generated by toki v")).toBe(true);
  });

  it("writer leaves sibling files alone but cleans only targeted subdirs", async () => {
    const outputDir = await uniqueDir();
    // Pre-existing user file under the output root must survive a clean build.
    await mkdir(join(outputDir, "keep-me"), { recursive: true });
    await writeFile(join(outputDir, "keep-me", "data.txt"), "persist", "utf8");

    const inputDir = await uniqueDir();
    const inputPath = join(inputDir, "tokens.json");
    await writeFile(inputPath, JSON.stringify(sampleDoc), "utf8");
    const result = await runPipeline({ input: inputPath, formats: ["css"] });
    await writeArtifacts(outputDir, result.artifacts, { clean: true });

    // keep-me directory and its file survived.
    expect(await readFile(join(outputDir, "keep-me", "data.txt"), "utf8")).toBe("persist");
    // css/ subdirectory was created.
    expect(await readdir(join(outputDir, "css"))).toContain("tokens.css");
  });

  it("resolveFormats accepts comma-free lists and rejects unknown formats", () => {
    expect(resolveFormats(["css", "js"])).toEqual(["css", "js"]);
    expect(() => resolveFormats(["css", "react"])).toThrow(/Unknown or unimplemented/);
  });
});