/**
 * Core type definitions for the Toki design token pipeline.
 *
 * The pipeline transforms W3C Design Tokens Community Group (DTCG) JSON into
 * framework-specific code artifacts:
 *
 *   Parse → Resolve → Transform → Generate → Write
 *
 * Type hierarchy:
 * - `TokenGroupNode` — an interior node in the parsed tree (a "group").
 * - `DesignToken`    — a leaf node carrying a `$value`.
 * - `TokenNode`      — a discriminated union of the two (discriminated via `kind`).
 * - `ResolvedToken`  — a leaf token after reference expansion + `$type` inheritance.
 */

/** All `$type` values supported by Toki. */
export type TokenType =
  | 'color'
  | 'dimension'
  | 'fontFamily'
  | 'fontWeight'
  | 'duration'
  | 'cubicBezier'
  | 'number'
  | 'lineHeight'
  | 'letterSpacing'
  | 'shadow'
  | 'typography'
  | 'border'
  | 'transition';

/** Readonly set of valid `TokenType` values for runtime validation. */
export const TOKEN_TYPES: ReadonlySet<string> = new Set<TokenType>([
  'color',
  'dimension',
  'fontFamily',
  'fontWeight',
  'duration',
  'cubicBezier',
  'number',
  'lineHeight',
  'letterSpacing',
  'shadow',
  'typography',
  'border',
  'transition',
]);

/** Reserved top-level DTCG property keys (the `$`-prefixed ones). */
export const RESERVED_KEYS = ['$type', '$value', '$description', '$extensions'] as const;
export type ReservedKey = (typeof RESERVED_KEYS)[number];

/**
 * A raw token value. May be a primitive (color/dimension/number/...), a plain
 * object (composite types like `shadow` / `typography`, or `$extensions`), or
 * an array (e.g. `cubicBezier` control points, multi-shadow lists).
 *
 * References (`{group.token}`) may appear inside string values; the resolver
 * expands them into concrete values.
 */
export type TokenValue = string | number | boolean | TokenComposite | readonly TokenValue[];

/** A composite (object) token value — used by `shadow`, `typography`, `border`, `transition`. */
export type TokenComposite = Readonly<Record<string, unknown>>;

/** Discriminator union node type. */
export type TokenNodeKind = 'group' | 'token';

/**
 * Interior group node. Group `$type` propagates to descendant tokens unless
 * overridden by a nearer group or the token itself.
 */
export interface TokenGroupNode {
  readonly kind: 'group';
  readonly name: string;
  readonly path: readonly string[];
  readonly children: Readonly<Record<string, TokenNode>>;
  readonly $type?: TokenType;
  readonly $description?: string;
  readonly $extensions?: Readonly<Record<string, unknown>>;
}

/**
 * Leaf design token — carries a raw `$value` (which may include references).
 * `$type` is optional here; the resolver applies inheritance if it is absent.
 */
export interface DesignToken {
  readonly kind: 'token';
  readonly id: string;
  readonly name: string;
  readonly path: readonly string[];
  readonly $value: TokenValue;
  readonly $type?: TokenType;
  readonly $description?: string;
  readonly $extensions?: Readonly<Record<string, unknown>>;
}

/** Any node in the parsed token tree. */
export type TokenNode = TokenGroupNode | DesignToken;

/** The parsed token tree (root is always a group). */
export type TokenTree = TokenGroupNode;

/**
 * Normalized document returned by the parser: the full tree plus a flat list
 * of leaf tokens (in document order) for convenient access.
 */
export interface DesignTokenDocument {
  readonly tree: TokenTree;
  readonly tokens: readonly DesignToken[];
}

/**
 * A fully resolved leaf token: references expanded and concrete `$type`
 * assigned (explicit value or inherited from the nearest group).
 */
export interface ResolvedToken {
  readonly path: readonly string[];
  /** Dotted path usable as a stable identifier, e.g. `color.primary`. */
  readonly id: string;
  readonly name: string;
  readonly type: TokenType;
  /** Concrete value — no references remain. */
  readonly value: TokenValue;
  readonly description?: string;
  readonly extensions?: Readonly<Record<string, unknown>>;
}

/** Output formats Toki can generate. Phase 1 ships `css` and `js`. */
export type OutputFormat = 'css' | 'js' | 'react-native' | 'angular' | 'angular-11' | 'svelte' | 'react' | 'stencil' | 'vue' | 'tailwind';

/** All output formats supported by the generator registry. */
export const ALL_FORMATS: readonly OutputFormat[] = [
  'css',
  'js',
  'react-native',
  'angular',
  'angular-11',
  'svelte',
  'react',
  'stencil',
  'vue',
  'tailwind',
];

/** A generated artifact ready to be written to disk. */
export interface OutputArtifact {
  /** Path relative to the output directory (POSIX, forward slashes). */
  readonly relativePath: string;
  readonly format: OutputFormat;
  readonly content: string;
}

/** Options passed to a generator. */
export interface GeneratorOptions {
  /** Toki package version, used in the `Generated by toki v{version}` header. */
  readonly version: string;
  /** Theme name when running multi-theme builds. Affects output file naming. */
  readonly theme?: string;
  /** Naming convention override for this format. */
  readonly naming?: NamingConvention;
}

/** A platform generator module. */
export interface Generator {
  readonly format: OutputFormat;
  generate(tokens: readonly ResolvedToken[], options: GeneratorOptions): readonly OutputArtifact[];
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/** Supported naming conventions for token identifiers. */
export type NamingConvention = 'camelCase' | 'kebab-case' | 'CONSTANT_CASE' | 'SCREAMING_SNAKE_CASE';

/**
 * A user-defined transform function that modifies resolved tokens before
 * generation. Transforms execute in registration order after built-in
 * platform transformers.
 */
export type TransformPlugin = (token: ResolvedToken, context: TransformContext) => ResolvedToken;

/** Context passed to a transform plugin. */
export interface TransformContext {
  readonly platform: OutputFormat;
}

/**
 * Toki configuration file schema. Loaded from `toki.config.ts` (or `.js`).
 *
 * All fields except `input` and `output` are optional — sensible defaults
 * are applied when omitted.
 */
export interface TokiConfig {
  /** Input token file path(s) or glob patterns. */
  readonly input: string | readonly string[];
  /** Output directory for generated artifacts. */
  readonly output: string;
  /** Map of theme name → token file path for multi-theme builds. */
  readonly themes?: Readonly<Record<string, string>>;
  /** Output formats to generate. Defaults to `["css", "js"]`. */
  readonly formats?: readonly OutputFormat[];
  /** Per-format naming convention overrides. */
  readonly naming?: Partial<Record<OutputFormat, NamingConvention>>;
  /** Custom transform functions applied after built-in platform transforms. */
  readonly transforms?: readonly TransformPlugin[];
  /** Whether to clean output subdirectories before writing. Defaults to `true`. */
  readonly clean?: boolean;
}
